#!/usr/bin/env node
/**
 * Build one localized Base44 surface and vendor it into static/<id>/.
 *
 * build-canvas-surface.mjs and build-semi-surface.mjs were the same forty
 * lines twice, differing only in checkout path, base path and surface name.
 * All three now live in static/gallery/plugins.json, so a new plugin is a
 * catalogue entry rather than another copy of this script.
 *
 *   node scripts/build-surface.mjs canvas          # one plugin
 *   node scripts/build-surface.mjs --all           # every wired plugin
 *   node scripts/build-surface.mjs --list          # what the catalogue holds
 *
 * The checkout location can be overridden per plugin with an env var derived
 * from its id: canvas -> CANVAS_REPO, lyrics-shader-lab -> LYRICS_SHADER_LAB_REPO.
 */
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const catalog = JSON.parse(
  readFileSync(join(appRoot, "static", "gallery", "plugins.json"), "utf8"),
);

const expand = (p) => (p.startsWith("~") ? join(homedir(), p.slice(1)) : p);
const envKey = (id) => `${id.toUpperCase().replace(/-/g, "_")}_REPO`;

function checkoutFor(plugin) {
  const override = process.env[envKey(plugin.id)];
  if (override) return resolve(override);
  const root = expand(plugin.repoRoot || catalog.repoRoot);
  return join(root, plugin.repo);
}

/** A fresh export has no node_modules, and vite is resolved from the checkout. */
function ensureDeps(repo, id) {
  if (existsSync(join(repo, "node_modules"))) return;
  console.log(`  installing dependencies for ${id} (first build)…`);
  execFileSync("npm", ["install", "--no-audit", "--no-fund"], {
    cwd: repo,
    stdio: "inherit",
  });
}

/**
 * Generic page mount.
 *
 * The first surfaces each shipped a hand-written `<Name>Surface.jsx` in the
 * guest checkout: eighteen of them, none importing a single component from the
 * app they were localizing. That re-implements the export instead of vendoring
 * it, so the ejected UI is thrown away and drifts from the live app.
 *
 * A plugin with `page` set mounts the app's real page instead. Nothing in the
 * guest tree is edited: the stock `main.jsx` does `import App from "@/App.jsx"`,
 * so a pre-enforced resolver points that one specifier at a generated mount
 * module, and the page comes up under the providers App.jsx would have given it
 * minus AuthProvider -- which is the only reason a Base44 page needs a login.
 *
 * MemoryRouter, not BrowserRouter: pages use Link/useNavigate and createPageUrl
 * (a pure "/" + name), and a framed surface must not drive the shell's URL bar.
 *
 * Both files are generated per build and removed after it, so the checkout
 * stays a clean eject that `base44 eject` can overwrite.
 */
const MOUNT_FILE = "src/__localized-mount.jsx";
const MOUNT_CONFIG = "vite.localized.config.mjs";

function writeMountFiles(repo, plugin) {
  const src = join(repo, "src");
  const pageFile = ["jsx", "tsx"]
    .map((ext) => `pages/${plugin.page}.${ext}`)
    .find((rel) => existsSync(join(src, rel)));
  if (!pageFile) {
    throw new Error(`${plugin.id}: no src/pages/${plugin.page}.jsx in ${repo}`);
  }

  // Only wire providers the guest actually ships. A Base44 export normally has
  // both, but the mount has to stay generic across app templates.
  const hasQuery = existsSync(join(src, "lib/query-client.js"));
  const hasToaster = existsSync(join(src, "components/ui/toaster.jsx"));

  const imports = [
    `import { MemoryRouter } from "react-router-dom";`,
    `import Page from "@/${pageFile.replace(/\.(jsx|tsx)$/, "")}";`,
  ];
  if (hasQuery) {
    imports.push(`import { QueryClientProvider } from "@tanstack/react-query";`);
    imports.push(`import { queryClientInstance } from "@/lib/query-client";`);
  }
  if (hasToaster) imports.push(`import { Toaster } from "@/components/ui/toaster";`);

  // The shell paints the panel behind the surface; the page keeps whatever
  // background of its own it sets.
  let tree = `<MemoryRouter initialEntries={["/${plugin.page}"]}>\n        <Page />${
    hasToaster ? "\n        <Toaster />" : ""
  }\n      </MemoryRouter>`;
  if (hasQuery) {
    tree = `<QueryClientProvider client={queryClientInstance}>\n      ${tree}\n    </QueryClientProvider>`;
  }

  writeFileSync(
    join(repo, MOUNT_FILE),
    `// Generated by scripts/build-surface.mjs -- removed when the build ends.\n` +
      `${imports.join("\n")}\n\n` +
      `document.documentElement.style.background = "transparent";\n` +
      `document.body.style.background = "transparent";\n\n` +
      `export default function LocalizedSurface() {\n  return (\n    ${tree}\n  );\n}\n`,
  );

  writeFileSync(
    join(repo, MOUNT_CONFIG),
    `// Generated by scripts/build-surface.mjs -- removed when the build ends.\n` +
      `import base44 from "@base44/vite-plugin";\n` +
      `import react from "@vitejs/plugin-react";\n` +
      `import { defineConfig } from "vite";\n` +
      `import { dirname, resolve } from "node:path";\n` +
      `import { fileURLToPath } from "node:url";\n\n` +
      `const root = dirname(fileURLToPath(import.meta.url));\n` +
      `const mount = resolve(root, "${MOUNT_FILE}");\n\n` +
      `export default defineConfig({\n` +
      `  logLevel: "error",\n` +
      `  plugins: [\n` +
      `    {\n` +
      `      // enforce:"pre" so this beats the plugin's own "@" alias.\n` +
      `      name: "localized-surface-mount",\n` +
      `      enforce: "pre",\n` +
      `      resolveId: (source) =>\n` +
      `        source === "@/App.jsx" || source === "./App.jsx" ? mount : null,\n` +
      `    },\n` +
      `    base44({\n` +
      `      // Pages import entities as @/entities/X, which only resolves with this.\n` +
      `      legacySDKImports: true,\n` +
      `      // Hosted-app scaffolding: none of it survives the move into the shell.\n` +
      `      hmrNotifier: false,\n` +
      `      navigationNotifier: false,\n` +
      `      analyticsTracker: false,\n` +
      `      visualEditAgent: false,\n` +
      `    }),\n` +
      `    react(),\n` +
      `  ],\n` +
      `});\n`,
  );
}

function build(plugin) {
  const { id, surface } = plugin;
  const repo = checkoutFor(plugin);
  const outDir = join(appRoot, "static", id);

  if (!existsSync(join(repo, "package.json"))) {
    throw new Error(`${id}: checkout not found at ${repo} — set ${envKey(id)}`);
  }

  console.log(`\n▸ ${plugin.name} (${id}) — surface "${surface}"`);
  console.log(`  from ${repo}`);
  ensureDeps(repo, id);

  if (plugin.page) writeMountFiles(repo, plugin);
  try {
    execFileSync(
      "npx",
      [
        "vite",
        "build",
        ...(plugin.page ? ["--config", MOUNT_CONFIG] : []),
        `--base=/static/${id}/`,
        "--outDir",
        "dist-surface",
      ],
      {
        cwd: repo,
        stdio: "inherit",
        // The surface build resolves its root module from this rather than from
        // ?surface=, so the bundle never carries the router, auth or the pages
        // behind them. See the guest's src/main.jsx.
        env: {
          ...process.env,
          VITE_LOCALIZED_PLUGIN_SURFACE: surface,
          // The plugin otherwise reads this from base44/.app.jsonc, which a
          // checkout only has if `base44 eject` got as far as linking it. The
          // catalogue knows the id either way.
          ...(plugin.appId ? { VITE_BASE44_APP_ID: plugin.appId } : {}),
        },
      },
    );
  } finally {
    if (plugin.page) {
      rmSync(join(repo, MOUNT_FILE), { force: true });
      rmSync(join(repo, MOUNT_CONFIG), { force: true });
    }
  }

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  cpSync(join(repo, "dist-surface"), outDir, { recursive: true });

  // A Base44 export ships a base44.com favicon, a manifest that 404s here and a
  // page-view beacon. Strip them on the way in, every time.
  execFileSync("node", [join(appRoot, "scripts", "sanitize-plugin-surface.mjs"), id], {
    stdio: "inherit",
  });
  console.log(`  vendored into static/${id}/`);
}

const args = process.argv.slice(2);
const buildable = catalog.plugins.filter((p) => p.repo && !p.serves);

if (args.includes("--list") || args.length === 0) {
  const width = Math.max(...catalog.plugins.map((p) => p.id.length));
  for (const p of catalog.plugins) {
    const built = existsSync(join(appRoot, "static", p.id, "index.html"));
    console.log(
      `${p.id.padEnd(width)}  ${p.state.padEnd(7)}  ${built ? "built" : "     "}  ` +
        `surface=${p.surface}${p.repo ? "" : "  (in-tree source)"}`,
    );
  }
  if (args.length === 0) console.log("\nUsage: build-surface.mjs <id> | --all | --list");
  process.exit(0);
}

const targets = args.includes("--all")
  ? buildable
  : args.map((id) => {
      const found = catalog.plugins.find((p) => p.id === id);
      if (!found) throw new Error(`Unknown plugin id "${id}" — see --list`);
      if (found.serves) throw new Error(`${id} is an alias for the ${found.serves} bundle — build that instead`);
      if (!found.repo) throw new Error(`${id} builds from in-tree source; use its own npm script`);
      return found;
    });

let failed = 0;
for (const plugin of targets) {
  try {
    build(plugin);
  } catch (error) {
    failed++;
    console.error(`  ✗ ${plugin.id}: ${error.message.split("\n")[0]}`);
    if (targets.length === 1) process.exit(1);
  }
}
if (failed) {
  console.error(`\n${failed} of ${targets.length} surfaces failed to build.`);
  process.exit(1);
}
